
export const chrysalisVariants = [
    {
      date: "2025-01-01",
      name: "Genesis Seed",
      description: "The first potential of a new year's growth.",
      icon: "Sprout",
    },
    {
      date: "2025-01-02",
      name: "Thawing Soil",
      description: "The earth softens, preparing for life.",
      icon: "Droplets",
    },
    {
      date: "2025-01-03",
      name: "Root's Whisper",
      description: "A silent stirring deep beneath the surface.",
      icon: "Wind",
    },
    {
      date: "2025-01-04",
      name: "Winter Sun",
      description: "A low, pale light offering distant warmth.",
      icon: "Sun",
    },
    {
      date: "2025-01-05",
      name: "Mycelial Web",
      description: "The unseen network connecting all life.",
      icon: "Network",
    },
    {
      date: "2025-01-06",
      name: "First Frost",
      description: "A delicate, crystalline blanket on the land.",
      icon: "Snowflake",
    },
    {
      date: "2025-01-07",
      name: "Dormant Bud",
      description: "Life waits patiently for the right moment.",
      icon: "Moon",
    },
    {
      date: "2025-01-08",
      name: "Stone's Patience",
      description: "The slow, silent witness to seasons.",
      icon: "Mountain",
    },
    {
      date: "2025-01-09",
      name: "Creek's Murmur",
      description: "The gentle sound of water over rock.",
      icon: "Waves",
    },
    {
      date: "2025-01-10",
      name: "Silent Forest",
      description: "A cathedral of trees in quiet repose.",
      icon: "Trees",
    },
    {
      date: "2025-01-11",
      name: "Fallen Leaf",
      description: "Returning nutrients to the soil from which it came.",
      icon: "Leaf",
    },
    {
      date: "2025-01-12",
      name: "Bark's Shield",
      description: "Protecting the heartwood from the cold.",
      icon: "Shield",
    },
    {
      date: "2025-01-13",
      name: "Hollow Log",
      description: "A hidden shelter for the smallest creatures.",
      icon: "Home",
    },
    {
      date: "2025-01-14",
      name: "Crow's Call",
      description: "A sharp, intelligent voice in the winter air.",
      icon: "Bird",
    },
    {
      date: "2025-01-15",
      name: "Pine's Scent",
      description: "The sharp, clean fragrance of evergreen life.",
      icon: "TreePine",
    },
    {
      date: "2025-01-16",
      name: "Frozen Puddle",
      description: "A temporary window of solid water.",
      icon: "Slice",
    },
    {
      date: "2025-01-17",
      name: "Night's Stillness",
      description: "The world holds its breath under the stars.",
      icon: "Star",
    },
    {
      date: "2025-01-18",
      name: "Fungal Spore",
      description: "A universe of potential in a single speck.",
      icon: "Circle",
    },
    {
      date: "2025-01-19",
      name: "Animal Track",
      description: "A story written in the snow.",
      icon: "Footprints",
    },
    {
      date: "2025-01-20",
      name: "Lichen's Grip",
      description: "A partnership of life clinging to stone.",
      icon: "Anchor",
    },
    {
      date: "2025-01-21",
      name: "The Deepest Root",
      description: "Searching for water in the dark earth.",
      icon: "MoveVertical",
    },
    {
      date: "2025-01-22",
      name: "Winter's Howl",
      description: "The wind's song through bare branches.",
      icon: "Tornado",
    },
    {
      date: "2025-01-23",
      name: "Aged Humus",
      description: "The rich, dark result of decay and life.",
      icon: "Layers",
    },
    {
      date: "2025-01-24",
      name: "Seed's Promise",
      description: "A future forest held in your hand.",
      icon: "Package",
    },
    {
      date: "2025-01-25",
      name: "Geode's Secret",
      description: "A plain stone holding a crystal heart.",
      icon: "Gem",
    },
    {
      date: "2025-01-26",
      name: "Stream's Bend",
      description: "The water finds its own path.",
      icon: "Spline",
    },
    {
      date: "2025-01-27",
      name: "Worm's Passage",
      description: "The tireless aerator of the soil.",
      icon: "Milestone",
    },
    {
      date: "2025-01-28",
      name: "Rising Sap",
      description: "The slow awakening within the tree.",
      icon: "ArrowUp",
    },
    {
      date: "2025-01-29",
      name: "Mossy Carpet",
      description: "A soft, green floor for the forest.",
      icon: "BedDouble",
    },
    {
      date: "2025-01-30",
      name: "The Longest Night",
      description: "A turning point towards the light.",
      icon: "Sunset",
    },
    {
      date: "2025-01-31",
      name: "Glimmer of Spring",
      description: "The first faint hint of the coming warmth.",
      icon: "Sunrise",
    },
    {
      date: "2025-02-01",
      name: "Crocus Bud",
      description: "A brave spear of color through the snow.",
      icon: "Flower",
    },
    {
      date: "2025-02-02",
      name: "Melting Ice",
      description: "The sound of transition from solid to liquid.",
      icon: "Thermometer",
    },
    {
      date: "2025-02-03",
      name: "Robin's Return",
      description: "A cheerful sign that warmth is near.",
      icon: "Bird",
    },
    {
      date: "2025-02-04",
      name: "Soft Rain",
      description: "A gentle drink for the thirsty earth.",
      icon: "CloudRain",
    },
    {
      date: "2025-02-05",
      name: "Swelling Twig",
      description: "New life pushing against its confines.",
      icon: "Plus",
    },
    {
      date: "2025-02-06",
      name: "Muddy Path",
      description: "The ground softens, a sign of the thaw.",
      icon: "Waypoints",
    },
    {
      date: "2025-02-07",
      name: "First Green Shoot",
      description: "A tiny flag of life unfurling.",
      icon: "LeafyGreen",
    },
    {
      date: "2025-02-08",
      name: "Awakening Bee",
      description: "A low buzz signals the start of pollination.",
      icon: "Bug",
    },
    {
      date: "2025-02-09",
      name: "Longer Days",
      description: "The sun lingers, encouraging growth.",
      icon: "Clock",
    },
    {
      date: "2025-02-10",
      name: "Pussy Willow",
      description: "A soft, furry promise of the coming spring.",
      icon: "PawPrint",
    },
    {
      date: "2025-02-11",
      name: "Clearing Fog",
      description: "The world comes into focus once more.",
      icon: "CloudFog",
    },
    {
      date: "2025-02-12",
      name: "Earth's Breath",
      description: "The scent of damp soil and new life.",
      icon: "AirVent",
    },
    {
      date: "2025-02-13",
      name: "Unfurling Fern",
      description: "A spiral of life reaching for the light.",
      icon: "UnfoldVertical",
    },
    {
      date: "2025-02-14",
      name: "Nesting Pair",
      description: "Two birds building a home together.",
      icon: "Heart",
    },
    {
      date: "2025-02-15",
      name: "Tadpole's Wriggle",
      description: "The beginning of a great transformation.",
      icon: "Fish",
    },
    {
      date: "2025-02-16",
      name: "Spring Equinox",
      description: "The perfect balance of day and night.",
      icon: "CircleEqual",
    },
    {
      date: "2025-02-17",
      name: "Cherry Blossom",
      description: "A fleeting, beautiful cloud of pink.",
      icon: "Cherry",
    },
    {
      date: "2025-02-18",
      name: "Bumblebee's Dance",
      description: "A fuzzy messenger carrying life between flowers.",
      icon: "MessageCircle",
    },
    {
      date: "2025-02-19",
      name: "Dandelion Seed",
      description: "A parachute carrying a wish on the wind.",
      icon: "Send",
    },
    {
      date: "2025-02-20",
      name: "Verdant Canopy",
      description: "The world turns a vibrant, living green.",
      icon: "Umbrella",
    },
    {
      date: "2025-02-21",
      name: "Morning Dew",
      description: "Tiny jewels scattered across every surface.",
      icon: "Gem",
    },
    {
      date: "2025-02-22",
      name: "Ladybug's Ascent",
      description: "A small, bright guardian of the garden.",
      icon: "Aperture",
    },
    {
      date: "2025-02-23",
      name: "Pollen Cloud",
      description: "A golden haze, the very essence of creation.",
      icon: "Cloud",
    },
    {
      date: "2025-02-24",
      name: "Fawn's First Steps",
      description: "A wobbly, new life in a sun-dappled glade.",
      icon: "Baby",
    },
    {
      date: "2025-02-25",
      name: "Ant's Trail",
      description: "A disciplined line of workers, each with a purpose.",
      icon: "Spline",
    },
    {
      date: "2025-02-26",
      name: "Flowing River",
      description: "The lifeblood of the landscape, carving its path.",
      icon: "Waypoints",
    },
    {
      date: "2025-02-27",
      name: "Caterpillar's Hunger",
      description: "Fueling the great change that is to come.",
      icon: "Bug",
    },
    {
      date: "2025-02-28",
      name: "Spider's Web",
      description: "An intricate, dewy trap spun in the dawn.",
      icon: "Bug",
    },
    {
      date: "2025-02-29",
      name: "Leap of Faith",
      description: "An extra day for growth and possibility.",
      icon: "Rabbit",
    },
    {
      date: "2025-03-01",
      name: "Budburst",
      description: "The moment a leaf breaks free.",
      icon: "GitCommitVertical",
    },
    {
      date: "2025-03-02",
      name: "Fiddlehead",
      description: "A coiled fern, ancient and full of promise.",
      icon: "Radiation",
    },
    {
      date: "2025-03-03",
      name: "Warm Breeze",
      description: "A soft wind carrying the scent of flowers.",
      icon: "Feather",
    },
    {
      date: "2025-03-04",
      name: "Sprouting Seed",
      description: "The first push of life against gravity.",
      icon: "TrendingUp",
    },
    {
      date: "2025-03-05",
      name: "Songbird's Melody",
      description: "The complex, beautiful language of the air.",
      icon: "Music",
    },
    {
      date: "2025-03-06",
      name: "Thistle's Defense",
      description: "A beautiful flower protected by its thorns.",
      icon: "Grape",
    },
    {
      date: "2025-03-07",
      name: "Sun-warmed Stone",
      description: "A place for a lizard to bask and dream.",
      icon: "SunMedium",
    },
    {
      date: "2025-03-08",
      name: "Hummingbird's Hover",
      description: "A tiny, iridescent engine of pollination.",
      icon: "Zap",
    },
    {
      date: "2025-03-09",
      name: "Peat's History",
      description: "Layers of time compressed into rich earth.",
      icon: "Library",
    },
    {
      date: "2025-03-10",
      name: "Vine's Climb",
      description: "Reaching for sunlight by embracing others.",
      icon: "GitBranch",
    },
    {
      date: "2025-03-11",
      name: "Dragonfly's Dart",
      description: "A flash of color over a still pond.",
      icon: "Plane",
    },
    {
      date: "2025-03-12",
      name: "Spring Tide",
      description: "The powerful pull of the moon on the water.",
      icon: "RefreshCcw",
    },
    {
      date: "2025-03-13",
      name: "Mushroom's Cap",
      description: "The fruiting body of a vast, hidden network.",
      icon: "Brain",
    },
    {
      date: "2025-03-14",
      name: "Butterfly's Emergence",
      description: "A winged jewel breaks free from its chrysalis.",
      icon: "Award",
    },
    {
      date: "2025-03-15",
      name: "Thundershower",
      description: "A dramatic, life-giving burst of rain.",
      icon: "CloudLightning",
    },
    {
      date: "2025-03-16",
      name: "Rainbow's Arc",
      description: "A fleeting bridge of color after the storm.",
      icon: "Palette",
    },
    {
      date: "2025-03-17",
      name: "Clover's Luck",
      description: "A field of green, a symbol of fortune.",
      icon: "Clover",
    },
    {
      date: "2025-03-18",
      name: "Gopher's Tunnel",
      description: "A hidden world of passages under the meadow.",
      icon: "Torus",
    },
    {
      date: "2025-03-19",
      name: "Wildflower Meadow",
      description: "A chaotic, beautiful tapestry of color.",
      icon: "Flower2",
    },
    {
      date: "2025-03-20",
      name: "Grazing Herd",
      description: "The gentle shaping of the landscape by herbivores.",
      icon: "Beef",
    },
    {
      date: "2025-03-21",
      name: "Osprey's Dive",
      description: "A swift, precise hunter of the waterways.",
      icon: "Anchor",
    },
    {
      date: "2025-03-22",
      name: "Forest Floor",
      description: "A complex community of decay and rebirth.",
      icon: "Recycle",
    },
    {
      date: "2025-03-23",
      name: "Garnet Clay",
      description: "Rich, red earth, full of iron and potential.",
      icon: "PaintBucket",
    },
    {
      date: "2025-03-24",
      name: "Dappled Sunlight",
      description: "Light filtering through a new leaf canopy.",
      icon: "SunSnow",
    },
    {
      date: "2025-03-25",
      name: "Boreal Forest",
      description: "The vast, wild expanse of the northern woods.",
      icon: "TreeDeciduous",
    },
    {
      date: "2025-03-26",
      name: "River Delta",
      description: "Where the river meets the sea, creating new land.",
      icon: "Landmark",
    },
    {
      date: "2025-03-27",
      name: "Coastal Tidepool",
      description: "A miniature world left behind by the ocean.",
      icon: "Starfish",
    },
    {
      date: "2025-03-28",
      name: "Coral Reef",
      description: "A vibrant underwater city built by tiny creatures.",
      icon: "Network",
    },
    {
      date: "2025-03-29",
      name: "Volcanic Vent",
      description: "Life finding a way in the most extreme places.",
      icon: "Flame",
    },
    {
      date: "2025-03-30",
      name: "Glacier's Carve",
      description: "The slow, powerful sculpting of a valley.",
      icon: "Axe",
    },
    {
      date: "2025-03-31",
      name: "Sand Dune's Crest",
      description: "A shifting mountain of sand, shaped by wind.",
      icon: "GalleryVertical",
    },
    {
      date: "2025-04-01",
      name: "April Shower",
      description: "Bringing the promise of May flowers.",
      icon: "ShowerHead",
    },
    {
      date: "2025-04-02",
      name: "Earthworm Casting",
      description: "The richest soil, a gift from a humble creature.",
      icon: "Gift",
    },
    {
      date: "2025-04-03",
      name: "Blossom's Fall",
      description: "A petal shower, making way for fruit.",
      icon: "MoveDown",
    },
    {
      date: "2025-04-04",
      name: "Eaglet's Cry",
      description: "A new predator's voice in the high aerie.",
      icon: "ChevronsUp",
    },
    {
      date: "2025-04-05",
      name: "Guppy's School",
      description: "A shimmering, darting community in the water.",
      icon: "Users",
    },
    {
      date: "2025-04-06",
      name: "Willow's Weep",
      description: "Graceful branches touching the water's surface.",
      icon: "Droplet",
    },
    {
      date: "2025-04-07",
      name: "Bluebird's Flash",
      description: "A startlingly bright messenger of happiness.",
      icon: "Sparkle",
    },
    {
      date: "2025-04-08",
      name: "Solar Eclipse",
      description: "A moment of cosmic alignment, a shadow on the earth.",
      icon: "CircleDashed",
    },
    {
      date: "2025-04-09",
      name: "Cricket's Chirp",
      description: "The rhythmic thermometer of the evening air.",
      icon: "AudioWaveform",
    },
    {
      date: "2025-04-10",
      name: "Sapling's Bend",
      description: "Flexibility and resilience in the face of wind.",
      icon: "RefreshCw",
    },
    {
      date: "2025-04-11",
      name: "Daffodil Trumpet",
      description: "A bright yellow announcement of spring's arrival.",
      icon: "Megaphone",
    },
    {
      date: "2025-04-12",
      name: "Busy Beaver",
      description: "An industrious architect of waterways.",
      icon: "Construction",
    },
    {
      date: "2025-04-13",
      name: "Lily Pad's Platform",
      description: "A floating stage for a frog's song.",
      icon: "Disc",
    },
    {
      date: "2025-04-14",
      name: "Hawk's Circle",
      description: "A patient, soaring search for sustenance.",
      icon: "CircleDot",
    },
    {
      date: "2025-04-15",
      name: "Turtle's Shell",
      description: "A slow, ancient home, a map of long life.",
      icon: "Shield",
    },
    {
      date: "2025-04-16",
      name: "Firefly's Light",
      description: "A blinking, magical conversation in the dusk.",
      icon: "Lightbulb",
    },
    {
      date: "2025-04-17",
      name: "Cattail's Stand",
      description: "A dense, brown community at the water's edge.",
      icon: "Columns",
    },
    {
      date: "2025-04-18",
      name: "Garter Snake's Slither",
      description: "A silent, striped hunter in the undergrowth.",
      icon: "MoveHorizontal",
    },
    {
      date: "2025-04-19",
      name: "Moth's Wing",
      description: "A dusty, intricate pattern drawn to the moon.",
      icon: "MoonStar",
    },
    {
      date: "2025-04-20",
      name: "Photosynthesis",
      description: "The quiet miracle of turning light into life.",
      icon: "SunDim",
    },
    {
      date: "2025-04-21",
      name: "Bioluminescence",
      description: "Life that creates its own light in the deep.",
      icon: "Projector",
    },
    {
      date: "2025-04-22",
      name: "Earth Day",
      description: "A global recognition of our planet's value.",
      icon: "Globe",
    },
    {
      date: "2025-04-23",
      name: "Geyser's Eruption",
      description: "The earth's powerful release of steam and water.",
      icon: "ArrowBigUp",
    },
    {
      date: "2025-04-24",
      name: "Petrichor",
      description: "The distinct, earthy scent of rain on dry soil.",
      icon: "BrainCircuit",
    },
    {
      date: "2025-04-25",
      name: "Symbiosis",
      description: "Two different lives, thriving together.",
      icon: "Handshake",
    },
    {
      date: "2025-04-26",
      name: "Mangrove Forest",
      description: "A tangle of roots standing strong against the tide.",
      icon: "Cable",
    },
    {
      date: "2025-04-27",
      name: "Stalactite's Drip",
      description: "The slow, patient creation of stone.",
      icon: "Paintbrush",
    },
    {
      date: "2025-04-28",
      name: "Alpine Tundra",
      description: "Tiny, tough flowers above the treeline.",
      icon: "Shrub",
    },
    {
      date: "2025-04-29",
      name: "Kelp Forest",
      description: "A swaying, underwater world of green.",
      icon: "Vegan",
    },
    {
      date: "2025-04-30",
      name: "Canyon's Echo",
      description: "A voice returned by ancient stone walls.",
      icon: "Reply",
    },
    {
      date: "2025-05-01",
      name: "May Day Bloom",
      description: "A celebration of fertility and new life.",
      icon: "PartyPopper",
    },
    {
      date: "2025-05-02",
      name: "Humus Layer",
      description: "The dark, rich foundation of the forest.",
      icon: "FileBox",
    },
    {
      date: "2025-05-03",
      name: "Swarm's Intelligence",
      description: "A collective mind moving as one.",
      icon: "Grid",
    },
    {
      date: "2025-05-04",
      name: "Sturgeon's Age",
      description: "An ancient, armored fish of the deep rivers.",
      icon: "Bone",
    },
    {
      date: "2025-05-05",
      name: "Cactus Flower",
      description: "A rare, stunning bloom in the harshest land.",
      icon: "Star",
    },
    {
      date: "2025-05-06",
      name: "Lightning Strike",
      description: "A sudden, powerful exchange of energy.",
      icon: "Zap",
    },
    {
      date: "2025-05-07",
      name: "Wildfire's Renewal",
      description: "Destruction that clears the way for new growth.",
      icon: "FlameKindling",
    },
    {
      date: "2025-05-08",
      name: "Fairy Ring",
      description: "A circle of mushrooms, a door to another world.",
      icon: "CircleEllipsis",
    },
    {
      date: "2025-05-09",
      name: "Oak's Strength",
      description: "A symbol of endurance, wisdom, and resilience.",
      icon: "Tree",
    },
    {
      date: "2025-05-10",
      name: "Topsoil's Treasure",
      description: "The thin, precious layer that feeds the world.",
      icon: "Coins",
    },
    {
      date: "2025-05-11",
      name: "Swallow's Nest",
      description: "A carefully crafted home of mud and saliva.",
      icon: "Construction",
    },
    {
      date: "2025-05-12",
      name: "Monarch's Migration",
      description: "A multi-generational journey of thousands of miles.",
      icon: "Map",
    },
    {
      date: "2025-05-13",
      name: "Cattail Fluff",
      description: "Seeds taking flight on a soft, white cloud.",
      icon: "CloudMoon",
    },
    {
      date: "2025-05-14",
      name: "Algae's Bloom",
      description: "A sudden explosion of green in still water.",
      icon: "Paintbrush2",
    },
    {
      date: "2025-05-15",
      name: "Praying Mantis",
      description: "A patient, alien-like hunter in the leaves.",
      icon: "Swords",
    },
    {
      date: "2025-05-16",
      name: "Dewy Spiderweb",
      description: "A perfect, jeweled net in the morning light.",
      icon: "Network",
    },
    {
      date: "2025-05-17",
      name: "Rolling Thunder",
      description: "The deep, resonant voice of a distant storm.",
      icon: "Drum",
    },
    {
      date: "2025-05-18",
      name: "Compost's Heat",
      description: "The warmth of millions of tiny lives at work.",
      icon: "Thermometer",
    },
    {
      date: "2025-05-19",
      name: "Morel Mushroom",
      description: "A elusive, honeycomb-like treasure of the woods.",
      icon: "BrainCog",
    },
    {
      date: "2025-05-20",
      name: "Hatching Egg",
      description: "A new life pecks its way into the world.",
      icon: "Egg",
    },
    {
      date: "2025-05-21",
      name: "Bioluminescent Bay",
      description: "The water glows with every movement.",
      icon: "Lightbulb",
    },
    {
      date: "2025-05-22",
      name: "Prairie Fire",
      description: "A cleansing force for the vast grasslands.",
      icon: "FireExtinguisher",
    },
    {
      date: "2025-05-23",
      name: "Pollinator's Path",
      description: "The invisible highways connecting flowering plants.",
      icon: "Bug",
    },
    {
      date: "2025-05-24",
      name: "Permafrost's Secret",
      description: "Ancient life held in a deep, icy sleep.",
      icon: "Package2",
    },
    {
      date: "2025-05-25",
      name: "Estuary's Mix",
      description: "Where freshwater and saltwater meet and mingle.",
      icon: "Blend",
    },
    {
      date: "2025-05-26",
      name: "Strangler Fig",
      description: "A tree that embraces another to reach the sky.",
      icon: "Grip",
    },
    {
      date: "2025-05-27",
      name: "Pitcher Plant",
      description: "A beautiful, carnivorous flower with a hidden trap.",
      icon: "Trash2",
    },
    {
      date: "2025-05-28",
      name: "Baobab's Girth",
      description: "An ancient, water-storing giant of the savanna.",
      icon: "CupSoda",
    },
    {
      date: "2025-05-29",
      name: "Termite Mound",
      description: "A massive, ventilated city built of earth.",
      icon: "Building",
    },
    {
      date: "2025-05-30",
      name: "Bat's Echo",
      description: "Seeing the world through sound in the night sky.",
      icon: "Radio",
    },
    {
      date: "2025-05-31",
      name: "The Green Flash",
      description: "A rare, fleeting ray at the moment of sunset.",
      icon: "Eye",
    },
    {
      date: "2025-06-01",
      name: "Summer Solstice",
      description: "The longest day, the peak of the sun's power.",
      icon: "Sun",
    },
    {
      date: "2025-06-02",
      name: "Ripening Berry",
      description: "A sweet, juicy gift from a summer bush.",
      icon: "Grape",
    },
    {
      date: "2025-06-03",
      name: "Cicada's Song",
      description: "The loud, buzzing drone of a hot afternoon.",
      icon: "RadioTower",
    },
    {
      date: "2025-06-04",
      name: "Verdant Growth",
      description: "The lush, unrestrained green of early summer.",
      icon: "MoveUp",
    },
    {
      date: "2025-06-05",
      name: "Lazy River",
      description: "A slow, meandering path through the landscape.",
      icon: "Shell",
    },
    {
      date: "2025-06-06",
      name: "Queen Bee's Court",
      description: "The heart of the hive, a center of creation.",
      icon: "Crown",
    },
    {
      date: "2025-06-07",
      name: "Sun-baked Clay",
      description: "The earth cracks and hardens under the heat.",
      icon: "Brick",
    },
    {
      date: "2025-06-08",
      name: "Pond Scum",
      description: "A vibrant, essential layer of life on still water.",
      icon: "Filter",
    },
    {
      date: "2025-06-09",
      name: "Thorn's Protection",
      description: "A sharp defense for a sweet fruit or flower.",
      icon: "ShieldAlert",
    },
    {
      date: "2025-06-10",
      name: "Basking Snake",
      description: "Absorbing the sun's energy on a warm rock.",
      icon: "Thermometer",
    },
    {
      date: "2025-06-11",
      name: "Shimmering Heat",
      description: "The air itself seems to dance in the high sun.",
      icon: "Haze",
    },
    {
      date: "2025-06-12",
      name: "Dandelion Clock",
      description: "Tell the time by blowing wishes to the wind.",
      icon: "Clock10",
    },
    {
      date: "2025-06-13",
      name: "Rushing Waterfall",
      description: "The powerful, constant sound of falling water.",
      icon: "Package",
    },
    {
      date: "2025-06-14",
      name: "Night-blooming Jasmine",
      description: "A heady scent released only after dark.",
      icon: "Moon",
    },
    {
      date: "2025-06-15",
      name: "Wolf's Howl",
      description: "A lonely, beautiful call to the pack.",
      icon: "Dog",
    },
    {
      date: "2025-06-16",
      name: "Seagrass Meadow",
      description: "An underwater prairie, a nursery for sea life.",
      icon: "Wheat",
    },
    {
      date: "2025-06-17",
      name: "Tidal Bore",
      description: "A wave that flows up a river against the current.",
      icon: "ArrowLeftRight",
    },
    {
      date: "2025-06-18",
      name: "Desert Oasis",
      description: "A sudden, miraculous pocket of water and life.",
      icon: "Palmtree",
    },
    {
      date: "2025-06-19",
      name: "Petrified Wood",
      description: "A tree that has slowly turned to stone.",
      icon: "Gem",
    },
    {
      date: "2025-06-20",
      name: "Aurora Borealis",
      description: "Cosmic winds painting the night sky.",
      icon: "MilkyWay",
    },
    {
      date: "2025-06-21",
      name: "Haboob's Wall",
      description: "A towering, dramatic storm of dust and sand.",
      icon: "Landmark",
    },
    {
      date: "2025-06-22",
      name: "Noctilucent Cloud",
      description: "Icy, electric blue clouds at the edge of space.",
      icon: "Cloudy",
    },
    {
      date: "2025-06-23",
      name: "Waterspout's Funnel",
      description: "A tornado that forms over water.",
      icon: "Tornado",
    },
    {
      date: "2025-06-24",
      name: "Foxfire's Glow",
      description: "The eerie, beautiful light of decaying wood.",
      icon: "EyeOff",
    },
    {
      date: "2025-06-25",
      name: "Red Tide",
      description: "A sudden, dramatic bloom of marine algae.",
      icon: "SwatchBook",
    },
    {
      date: "2025-06-26",
      name: "Ball Lightning",
      description: "A mysterious, hovering sphere of electrical energy.",
      icon: "Atom",
    },
    {
      date: "2025-06-27",
      name: "Morning Glory",
      description: "A massive, rolling cloud formation.",
      icon: "CloudSun",
    },
    {
      date: "2025-06-28",
      name: "Ice Circle",
      description: "A slowly rotating disc of ice in a river.",
      icon: "Disc2",
    },
    {
      date: "2025-06-29",
      name: "Brinicle's Descent",
      description: "An underwater icicle, a finger of death.",
      icon: "Fingerprint",
    },
    {
      date: "2025-06-30",
      name: "Lenticular Cloud",
      description: "A smooth, lens-shaped cloud, often mistaken for a UFO.",
      icon: "Torus",
    },
    {
      date: "2025-07-01",
      name: "High Summer",
      description: "The peak of heat and the fullness of life.",
      icon: "Sun",
    },
    {
      date: "2025-07-02",
      name: "Corn Tassel",
      description: "The golden, pollen-dusted crown of a corn stalk.",
      icon: "Carrot",
    },
    {
      date: "2025-07-03",
      name: "Wilting Leaf",
      description: "A plant's response to thirst under the hot sun.",
      icon: "TrendingDown",
    },
    {
      date: "2025-07-04",
      name: "Firework Bloom",
      description: "A man-made flower exploding in the night sky.",
      icon: "Sparkles",
    },
    {
      date: "2025-07-05",
      name: "Stifling Humidity",
      description: "The air is thick with water and warmth.",
      icon: "CloudDrizzle",
    },
    {
      date: "2025-07-06",
      name: "Dry Creek Bed",
      description: "A rocky path that waits for the rain.",
      icon: "Mouse",
    },
    {
      date: "2025-07-07",
      name: "Sunflower's Gaze",
      description: "A large, bright face that follows the sun.",
      icon: "Eye",
    },
    {
      date: "2025-07-08",
      name: "Grasshopper's Leap",
      description: "A sudden, powerful jump through the tall grass.",
      icon: "Footprints",
    },
    {
      date: "2025-07-09",
      name: "Bramble's Thicket",
      description: "An impenetrable, thorny fortress of berries.",
      icon: "Fence",
    },
    {
      date: "2025-07-10",
      name: "Doe's Stillness",
      description: "A moment of perfect camouflage and quiet.",
      icon: "PersonStanding",
    },
    {
      date: "2025-07-11",
      name: "Dust Devil's Dance",
      description: "A small, swirling vortex of wind and soil.",
      icon: "Tornado",
    },
    {
      date: "2025-07-12",
      name: "Mirage's Shimmer",
      description: "A trick of the light, a promise of water.",
      icon: "Image",
    },
    {
      date: "2025-07-13",
      name: "Burdock's Burr",
      description: "A clever seed that travels by clinging.",
      icon: "Paperclip",
    },
    {
      date: "2025-07-14",
      name: "Cattail's Pollen",
      description: "A cloud of yellow dust released to the wind.",
      icon: "Wind",
    },
    {
      date: "2025-07-15",
      name: "Bear's Scratch",
      description: "A territorial mark left on a tree trunk.",
      icon: "Hand",
    },
    {
      date: "2025-07-16",
      name: "Salmon's Leap",
      description: "A powerful struggle upstream to return home.",
      icon: "Fish",
    },
    {
      date: "2025-07-17",
      name: "Grizzly's Strength",
      description: "The raw, untamed power of a top predator.",
      icon: "Bone",
    },
    {
      date: "2025-07-18",
      name: "Avalanche's Roar",
      description: "The sudden, terrifying release of a mountain's snow.",
      icon: "MountainSnow",
    },
    {
      date: "2025-07-19",
      name: "Laurel's Wreath",
      description: "A symbol of victory and honor, a fragrant leaf.",
      icon: "Medal",
    },
    {
      date: "2025-07-20",
      name: "Quicksand's Pull",
      description: "Solid ground that is not what it seems.",
      icon: "LocateOff",
    },
    {
      date: "2025-07-21",
      name: "Maelstrom's Swirl",
      description: "A powerful, inescapable whirlpool.",
      icon: "Fan",
    },
    {
      date: "2025-07-22",
      name: "Supercell's Anvil",
      description: "The vast, flat top of a powerful thunderstorm.",
      icon: "Hammer",
    },
    {
      date: "2025-07-23",
      name: "Volcanic Ash",
      description: "Fine, fertile dust that falls from the sky.",
      icon: "LandPlot",
    },
    {
      date: "2025-07-24",
      name: "Tsunami's Wave",
      description: "The immense power of a displaced ocean.",
      icon: "Surf",
    },
    {
      date: "2025-07-25",
      name: "Amber's Prisoner",
      description: "Ancient life perfectly preserved in tree resin.",
      icon: "PackageOpen",
    },
    {
      date: "2025-07-26",
      name: "Fossil's Imprint",
      description: "A story of life written in stone.",
      icon: "Scroll",
    },
    {
      date: "2025-07-27",
      name: "Geothermal Pool",
      description: "Water heated by the earth's own inner fire.",
      icon: "Bath",
    },
    {
      date: "2025-07-28",
      name: "Saguaro's Arms",
      description: "A patient, iconic giant of the desert.",
      icon: "HelpingHand",
    },
    {
      date: "2025-07-29",
      name: "Salt Flat's Crust",
      description: "A vast, white expanse of crystallized minerals.",
      icon: "Square",
    },
    {
      date: "2025-07-30",
      name: "Mesa's Table",
      description: "A flat-topped mountain, a remnant of erosion.",
      icon: "Table",
    },
    {
      date: "2025-07-31",
      name: "Plateau's Vista",
      description: "A high, wide view of the world below.",
      icon: "View",
    },
    {
      date: "2025-08-01",
      name: "Dog Days' Haze",
      description: "The hazy, hot, and humid peak of summer.",
      icon: "Haze",
    },
    {
      date: "2025-08-02",
      name: "First Harvest",
      description: "Reaping the rewards of spring's hard work.",
      icon: "Wheat",
    },
    {
      date: "2025-08-03",
      name: "Zinnia's Burst",
      description: "A sturdy, cheerful flower that loves the heat.",
      icon: "Star",
    },
    {
      date: "2025-08-04",
      name: "Monsoon's Arrival",
      description: "The sudden, welcome onset of the rainy season.",
      icon: "CloudRainWind",
    },
    {
      date: "2025-08-05",
      name: "Blackberry's Stain",
      description: "The dark, sweet juice of a ripe summer berry.",
      icon: "Grape",
    },
    {
      date: "2025-08-06",
      name: "Wasp's Nest",
      description: "A paper fortress of hexagonal cells.",
      icon: "Hexagon",
    },
    {
      date: "2025-08-07",
      name: "Drought's Crack",
      description: "The earth splits open, thirsty for rain.",
      icon: "BetweenHorizontalEnd",
    },
    {
      date: "2025-08-08",
      name: "Locust's Swarm",
      description: "A devouring cloud, a force of nature.",
      icon: "Cloud",
    },
    {
      date: "2025-08-09",
      name: "Katydid's Rasp",
      description: "The sound of summer nights, a leg against a wing.",
      icon: "Music2",
    },
    {
      date: "2025-08-10",
      name: "Goldenrod's Plume",
      description: "A bright yellow sign of late summer.",
      icon: "Feather",
    },
    {
      date: "2025-08-11",
      name: "Perseid's Streak",
      description: "A meteor shower, wishes across the night sky.",
      icon: "Orbit",
    },
    {
      date: "2025-08-12",
      name: "Tomato's Weight",
      description: "A heavy, ripe fruit, full of summer sun.",
      icon: "Apple",
    },
    {
      date: "2025-08-13",
      name: "Hummingbird's Battle",
      description: "Tiny, fierce warriors defending their territory.",
      icon: "Swords",
    },
    {
      date: "2025-08-14",
      name: "Chigger's Bite",
      description: "An unseen irritant of the tall grass.",
      icon: "Bug",
    },
    {
      date: "2025-08-15",
      name: "Thistle's Down",
      description: "A soft, silky parachute for a prickly seed.",
      icon: "Airplay",
    },
    {
      date: "2025-08-16",
      name: "Fading Tan",
      description: "The sun's summer kiss begins to fade.",
      icon: "Watch",
    },
    {
      date: "2025-08-17",
      name: "Corn Maze",
      description: "A rustling, green labyrinth under the sun.",
      icon: "Puzzle",
    },
    {
      date: "2025-08-18",
      name: "Coyote's Yip",
      description: "A chorus of tricksters in the twilight.",
      icon: "Dog",
    },
    {
      date: "2025-08-19",
      name: "Gourd's Swell",
      description: "A future vessel or decoration takes shape.",
      icon: "Variable",
    },
    {
      date: "2025-08-20",
      name: "Harvest Moon",
      description: "A bright, full moon to light the gathering of crops.",
      icon: "Moon",
    },
    {
      date: "2025-08-21",
      name: "Migration's Urge",
      description: "An ancient instinct to move begins to stir.",
      icon: "Compass",
    },
    {
      date: "2025-08-22",
      name: "Delta's Formation",
      description: "Silt and sediment building new land at the river's mouth.",
      icon: "Triangle",
    },
    {
      date: "2025-08-23",
      name: "Atoll's Ring",
      description: "A circle of coral reef around a sunken island.",
      icon: "CircleDot",
    },
    {
      date: "2025-08-24",
      name: "Archipelago's Chain",
      description: "A series of islands, connected beneath the waves.",
      icon: "Link",
    },
    {
      date: "2025-08-25",
      name: "Peninsula's Reach",
      description: "A finger of land stretching out into the water.",
      icon: "MoveRight",
    },
    {
      date: "2025-08-26",
      name: "Isthmus's Bridge",
      description: "A narrow strip of land connecting two larger masses.",
      icon: "BetweenHorizontalStart",
    },
    {
      date: "2025-08-27",
      name: "Fjord's Walls",
      description: "A deep, narrow inlet carved by a glacier.",
      icon: "BetweenVerticalStart",
    },
    {
      date: "2025-08-28",
      name: "Lagoon's Calm",
      description: "A shallow body of water protected from the sea.",
      icon: "Shell",
    },
    {
      date: "2025-08-29",
      name: "Savanna's Grass",
      description: "A vast, golden sea under a wide African sky.",
      icon: "Wheat",
    },
    {
      date: "2025-08-30",
      name: "Steppe's Expanse",
      description: "A wide, treeless plain of grass.",
      icon: "Maximize2",
    },
    {
      date: "2025-08-31",
      name: "Taiga's Quiet",
      description: "The vast, snowy silence of the northern forest.",
      icon: "VolumeX",
    },
    {
      date: "2025-09-01",
      name: "Autumn Equinox",
      description: "Day and night in perfect, fleeting balance.",
      icon: "Scale",
    },
    {
      date: "2025-09-02",
      name: "First Fallen Leaf",
      description: "A single spot of color on the green grass.",
      icon: "Leaf",
    },
    {
      date: "2025-09-03",
      name: "Crisp Morning Air",
      description: "A new sharpness, a hint of the cold to come.",
      icon: "Wind",
    },
    {
      date: "2025-09-04",
      name: "Squirrel's Hoard",
      description: "A frantic, hidden collection of winter provisions.",
      icon: "Nut",
    },
    {
      date: "2025-09-05",
      name: "Golden Hour",
      description: "The soft, warm light of late afternoon.",
      icon: "Timer",
    },
    {
      date: "2025-09-06",
      name: "Acorn's Drop",
      description: "The fall of a future oak tree.",
      icon: "Tree",
    },
    {
      date: "2025-09-07",
      name: "Spider's Balloon",
      description: "A silken thread to ride the autumn winds.",
      icon: "Sailboat",
    },
    {
      date: "2025-09-08",
      name: "Gaggle's V",
      description: "A formation of geese, heading for warmer skies.",
      icon: "ChevronDown",
    },
    {
      date: "2025-09-09",
      name: "Pumpkin's Promise",
      description: "A heavy, round vessel of autumn feasts.",
      icon: "Cookie",
    },
    {
      date: "2025-09-10",
      name: "Turning Colors",
      description: "The forest canopy becomes a painter's palette.",
      icon: "Palette",
    },
    {
      date: "2025-09-11",
      name: "Milkweed's Flight",
      description: "Silky, white parachutes carrying monarch potential.",
      icon: "Paperclip",
    },
    {
      date: "2025-09-12",
      name: "Frost on the Pumpkin",
      description: "The first kiss of winter on an autumn icon.",
      icon: "Snowflake",
    },
    {
      date: "2025-09-13",
      name: "Harvest's Bounty",
      description: "The culmination of a season of growth.",
      icon: "ShoppingBasket",
    },
    {
      date: "2025-09-14",
      name: "Owl's Hoot",
      description: "A soft, questioning voice in the cooling night.",
      icon: "Eye",
    },
    {
      date: "2025-09-15",
      name: "Rut's Challenge",
      description: "The clash of antlers, a contest of strength.",
      icon: "Swords",
    },
    {
      date: "2025-09-16",
      name: "Indian Summer",
      description: "A last, warm embrace before the winter cold.",
      icon: "Sun",
    },
    {
      date: "2025-09-17",
      name: "Mullein's Stalk",
      description: "A tall, fuzzy spire, a torch of the fields.",
      icon: "TowerControl",
    },
    {
      date: "2025-09-18",
      name: "Chipmunk's Cheek",
      description: "A furry pouch, impossibly full of seeds.",
      icon: "Wallet",
    },
    {
      date: "2025-09-19",
      name: "Shorter Days",
      description: "The darkness begins to reclaim the hours.",
      icon: "Clock",
    },
    {
      date: "2025-09-20",
      name: "Bonfire's Crackle",
      description: "The sound and scent of a gathering in the cool air.",
      icon: "Flame",
    },
    {
      date: "2025-09-21",
      name: "Woolly Bear's Band",
      description: "A fuzzy caterpillar, a forecaster of winter.",
      icon: "Bug",
    },
    {
      date: "2025-09-22",
      name: "Ginkgo's Gold",
      description: "A sudden, uniform shower of golden leaves.",
      icon: "Coins",
    },
    {
      date: "2025-09-23",
      name: "Hibernating Bear",
      description: "Entering a long sleep to wait out the cold.",
      icon: "BedDouble",
    },
    {
      date: "2025-09-24",
      name: "Chaga's Conk",
      description: "A woody, medicinal fungus on a birch tree.",
      icon: "Hammer",
    },
    {
      date: "2025-09-25",
      name: "Brittle Leaf",
      description: "The crunch underfoot, the sound of autumn.",
      icon: "AudioLines",
    },
    {
      date: "2025-09-26",
      name: "Apple's Crispness",
      description: "The sweet, sharp bite of a fall harvest.",
      icon: "Apple",
    },
    {
      date: "2025-09-27",
      name: "Salamander's Secret",
      description: "A hidden, jewel-like creature under a damp log.",
      icon: "Gem",
    },
    {
      date: "2025-09-28",
      name: "Seed Pod's Rattle",
      description: "A dry, percussive sound in the autumn wind.",
      icon: "Music3",
    },
    {
      date: "2025-09-29",
      name: "Turkey's Gobble",
      description: "A loud, rattling call in the autumn woods.",
      icon: "Bird",
    },
    {
      date: "2025-09-30",
      name: "Cattail's Explosion",
      description: "A burst of fluff, sending seeds everywhere.",
      icon: "Bomb",
    },
    {
      date: "2025-10-01",
      name: "October's Fire",
      description: "The peak of autumn color, a forest ablaze.",
      icon: "Flame",
    },
    {
      date: "2025-10-02",
      name: "Cornucopia",
      description: "A horn of plenty, a symbol of abundance.",
      icon: "Grape",
    },
    {
      date: "2025-10-03",
      name: "Witch Hazel's Bloom",
      description: "A strange, stringy flower that blooms in the fall.",
      icon: "Sparkle",
    },
    {
      date: "2025-10-04",
      name: "Bare Branches",
      description: "The stark, beautiful skeleton of a tree.",
      icon: "GitFork",
    },
    {
      date: "2025-10-05",
      name: "Muskrat's Lodge",
      description: "A dome of reeds and mud in the marsh.",
      icon: "Home",
    },
    {
      date: "2025-10-06",
      name: "Pheasant's Flush",
      description: "A sudden, startling explosion of wings.",
      icon: "Bird",
    },
    {
      date: "2025-10-07",
      name: "Osage Orange",
      description: "A large, lumpy, inedible 'brain fruit'.",
      icon: "Brain",
    },
    {
      date: "2025-10-08",
      name: "Groundhog's Burrow",
      description: "A deep, safe haven for the coming winter.",
      icon: "Torus",
    },
    {
      date: "2025-10-09",
      name: "Fading Light",
      description: "The days grow noticeably shorter, the nights longer.",
      icon: "Sunset",
    },
    {
      date: "2025-10-10",
      name: "Jack-o'-Lantern",
      description: "A carved pumpkin, a temporary, glowing face.",
      icon: "Smile",
    },
    {
      date: "2025-10-11",
      name: "Raccoon's Mask",
      description: "A clever, nocturnal forager of the neighborhood.",
      icon: "Eye",
    },
    {
      date: "2025-10-12",
      name: "Falling Needles",
      description: "Even the evergreens must shed something.",
      icon: "TreePine",
    },
    {
      date: "2025-10-13",
      name: "Opossum's Grin",
      description: "An ancient, toothy creature of the night.",
      icon: "Skull",
    },
    {
      date: "2025-10-14",
      name: "Last Warm Day",
      description: "A final gift of warmth before the deep cold.",
      icon: "Gift",
    },
    {
      date: "2025-10-15",
      name: "Decay's Scent",
      description: "The rich, earthy smell of decomposition.",
      icon: "Recycle",
    },
    {
      date: "2025-10-16",
      name: "Winterberry's Red",
      description: "A bright splash of color against a grey landscape.",
      icon: "Cherry",
    },
    {
      date: "2025-10-17",
      name: "Geese's Farewell",
      description: "The final, fading calls of the migrating flocks.",
      icon: "Voicemail",
    },
    {
      date: "2025-10-18",
      name: "Deer's Scrape",
      description: "A patch of bare earth, a sign of the rut.",
      icon: "Shovel",
    },
    {
      date: "2025-10-19",
      name: "Windigo's Breath",
      description: "A legendary, icy wind of the northern forests.",
      icon: "Tornado",
    },
    {
      date: "2025-10-20",
      name: "Tamarack's Gold",
      description: "A coniferous tree that turns gold and drops its needles.",
      icon: "Coins",
    },
    {
      date: "2025-10-21",
      name: "Fairy Snot",
      description: "A strange, jelly-like fungus appearing after rain.",
      icon: "Snail",
    },
    {
      date: "2025-10-22",
      name: "Wolf's Breath Fungus",
      description: "A puffball that releases a cloud of spores.",
      icon: "Cloud",
    },
    {
      date: "2025-10-23",
      name: "Bleeding Tooth Fungus",
      description: "A mushroom that oozes a thick, red liquid.",
      icon: "Droplets",
    },
    {
      date: "2025-10-24",
      name: "Dead Man's Fingers",
      description: "An eerie fungus that resembles blackened digits.",
      icon: "Hand",
    },
    {
      date: "2025-10-25",
      name: "Ghost Plant",
      description: "A pale, parasitic plant with no chlorophyll.",
      icon: "Ghost",
    },
    {
      date: "2025-10-26",
      name: "Vampire Moth",
      description: "A moth that has evolved to drink blood.",
      icon: "Moon",
    },
    {
      date: "2025-10-27",
      name: "Assassin Bug",
      description: "A predator that wears the corpses of its victims.",
      icon: "Backpack",
    },
    {
      date: "2025-10-28",
      name: "Corpse Flower",
      description: "A massive, beautiful flower that smells of death.",
      icon: "Flower2",
    },
    {
      date: "2025-10-29",
      name: "Zombie-Ant Fungus",
      description: "A fungus that controls its host before killing it.",
      icon: "Bug",
    },
    {
      date: "2025-10-30",
      name: "Goliath Birdeater",
      description: "The world's largest spider, a true giant.",
      icon: "Bug",
    },
    {
      date: "2025-10-31",
      name: "Samhain's Veil",
      description: "The thin place between the worlds of the living and the dead.",
      icon: "Key",
    },
    {
      date: "2025-11-01",
      name: "November's Grey",
      description: "A month of quiet, colorless waiting.",
      icon: "Cloudy",
    },
    {
      date: "2025-11-02",
      name: "First Snowfall",
      description: "A soft, silent blanket transforming the world.",
      icon: "Snowflake",
    },
    {
      date: "2025-11-03",
      name: "Stick Season",
      description: "The time of year when all the branches are bare.",
      icon: "GitCommit",
    },
    {
      date: "2025-11-04",
      name: "Misty Breath",
      description: "The visible sign of warmth in the cold air.",
      icon: "CloudFog",
    },
    {
      date: "2025-11-05",
      name: "Skunk Cabbage's Heat",
      description: "A strange plant that melts the snow around it.",
      icon: "Thermometer",
    },
    {
      date: "2025-11-06",
      name: "Ice on the Edges",
      description: "The first solid fringe on a pond or lake.",
      icon: "Square",
    },
    {
      date: "2025-11-07",
      name: "Sleeping Roots",
      description: "Life gathered deep in the earth, waiting.",
      icon: "Bed",
    },
    {
      date: "2025-11-08",
      name: "Vole's Tunnel",
      description: "A network of passages under the snow.",
      icon: "Torus",
    },
    {
      date: "2025-11-09",
      name: "Empty Nest",
      description: "A silent, woven reminder of summer's life.",
      icon: "Home",
    },
    {
      date: "2025-11-10",
      name: "Juncos' Arrival",
      description: "The 'snowbirds' appear, a sign of deep winter.",
      icon: "Bird",
    },
    {
      date: "2025-11-11",
      name: "Wind's Bite",
      description: "A new, sharper cold in the November gales.",
      icon: "Wind",
    },
    {
      date: "2025-11-12",
      name: "Frozen Waterfall",
      description: "A moment of powerful movement, captured in ice.",
      icon: "Image",
    },
    {
      date: "2025-11-13",
      name: "Glistening Frost",
      description: "A thick, crystalline coating on every surface.",
      icon: "Sparkles",
    },
    {
      date: "2025-11-14",
      name: "Rabbit's Fur",
      description: "A winter coat, changing from brown to white.",
      icon: "Rabbit",
    },
    {
      date: "2025-11-15",
      name: "Smell of Snow",
      description: "A distinct, clean scent in the air before a storm.",
      icon: "Brain",
    },
    {
      date: "2025-11-16",
      name: "Weasel's Track",
      description: "A tiny, fierce hunter's path in the new snow.",
      icon: "Footprints",
    },
    {
      date: "2025-11-17",
      name: "Sun Dog's Halo",
      description: "A ring of light around the low winter sun.",
      icon: "CircleDot",
    },
    {
      date: "2025-11-18",
      name: "Lake's Freeze",
      description: "The final sealing of the water under a sheet of ice.",
      icon: "Lock",
    },
    {
      date: "2025-11-19",
      name: "Grouse's Drum",
      description: "A deep, resonant beating of wings in the cold air.",
      icon: "Drum",
    },
    {
      date: "2025-11-20",
      name: "Hoarfrost's Feathers",
      description: "Intricate, feathery crystals of ice on branches.",
      icon: "Feather",
    },
    {
      date: "2025-11-21",
      name: "Ptarmigan's Camouflage",
      description: "A bird that becomes as white as the snow.",
      icon: "EyeOff",
    },
    {
      date: "2025-11-22",
      name: "Ice Crystal's Geometry",
      description: "The perfect, six-sided structure of a snowflake.",
      icon: "Hexagon",
    },
    {
      date: "2025-11-23",
      name: "Ermine's Cloak",
      description: "A weasel's pure white winter fur, a royal treasure.",
      icon: "Crown",
    },
    {
      date: "2025-11-24",
      name: "Snow Bunting's Flock",
      description: "A swirling, cheerful flock in a winter field.",
      icon: "Users",
    },
    {
      date: "2025-11-25",
      name: "Glacier Lily's Hope",
      description: "A flower that can bloom right at the edge of a glacier.",
      icon: "Flower",
    },
    {
      date: "2025-11-26",
      name: "Snow Flea's Jump",
      description: "Tiny springtails, active on the surface of the snow.",
      icon: "Bug",
    },
    {
      date: "2025-11-27",
      name: "Moose's Antler-Shed",
      description: "A massive, bony crown, dropped to the forest floor.",
      icon: "Trophy",
    },
    {
      date: "2025-11-28",
      name: "Thanksgiving's Rest",
      description: "A time of gratitude for the year's harvest.",
      icon: "Home",
    },
    {
      date: "2025-11-29",
      name: "Icicle's Point",
      description: "A sharp, clear dagger of frozen water.",
      icon: "Pen",
    },
    {
      date: "2025-11-30",
      name: "Deep Freeze",
      description: "The land settles into the heart of winter.",
      icon: "Refrigerator",
    },
    {
      date: "2025-12-01",
      name: "Winter Solstice",
      description: "The shortest day, a turning point toward light.",
      icon: "Sunrise",
    },
    {
      date: "2025-12-02",
      name: "Cardinal's Red",
      description: "A startlingly bright male against the white snow.",
      icon: "Bird",
    },
    {
      date: "2025-12-03",
      name: "Snowdrift's Curve",
      description: "A smooth, sculpted mound of wind-blown snow.",
      icon: "Spline",
    },
    {
      date: "2025-12-04",
      name: "Blue Shadow",
      description: "The long, cool-colored shadows on a sunny winter day.",
      icon: "Pipette",
    },
    {
      date: "2025-12-05",
      name: "Hickory's Nut",
      description: "A hard-shelled treasure, food for the winter.",
      icon: "Nut",
    },
    {
      date: "2025-12-06",
      name: "Winter Aconite",
      description: "A tiny, yellow flower that can bloom in the snow.",
      icon: "Flower",
    },
    {
      date: "2025-12-07",
      name: "Lynx's Paw",
      description: "A massive, furred foot, a natural snowshoe.",
      icon: "Footprints",
    },
    {
      date: "2025-12-08",
      name: "Creaking Ice",
      description: "The groaning, shifting sound of a frozen lake.",
      icon: "AudioWaveform",
    },
    {
      date: "2025-12-09",
      name: "Conifer's Cone",
      description: "A woody, protective vessel for future trees.",
      icon: "Package",
    },
    {
      date: "2025-12-10",
      name: "Chickadee's Call",
      description: "A cheerful, inquisitive voice in the winter quiet.",
      icon: "MessageSquare",
    },
    {
      date: "2025-12-11",
      name: "Mink's Slide",
      description: "A playful path down a snowy riverbank.",
      icon: "Shell",
    },
    {
      date: "2025-12-12",
      name: "Yule Log's Glow",
      description: "A celebration of warmth and light in the darkest time.",
      icon: "Flame",
    },
    {
      date: "2025-12-13",
      name: "Holly's Point",
      description: "A sharp, glossy leaf and a bright red berry.",
      icon: "Leaf",
    },
    {
      date: "2025-12-14",
      name: "Snowy Owl's Gaze",
      description: "A silent, white hunter of the winter fields.",
      icon: "Eye",
    },
    {
      date: "2025-12-15",
      name: "Mistletoe's Kiss",
      description: "A parasitic plant, a symbol of holiday truce.",
      icon: "HeartHandshake",
    },
    {
      date: "2025-12-16",
      name: "Arctic Fox's Coat",
      description: "A thick, pure white fur for the deepest cold.",
      icon: "Dog",
    },
    {
      date: "2025-12-17",
      name: "Caribou's Trek",
      description: "A long, difficult journey through the winter landscape.",
      icon: "Map",
    },
    {
      date: "2025-12-18",
      name: "Polar Bear's Strength",
      description: "The master of the arctic ice, a powerful hunter.",
      icon: "Bone",
    },
    {
      date: "2025-12-19",
      name: "Walrus's Tusk",
      description: "An ivory tool for hauling out onto the ice.",
      icon: "Anchor",
    },
    {
      date: "2025-12-20",
      name: "Narwhal's Horn",
      description: "A single, spiraled tooth, the unicorn of the sea.",
      icon: "Sword",
    },
    {
      date: "2025-12-21",
      name: "Penguin's Huddle",
      description: "A community of warmth against the Antarctic cold.",
      icon: "Users2",
    },
    {
      date: "2025-12-22",
      name: "Antarctic Tern's Journey",
      description: "The longest migration on earth, from pole to pole.",
      icon: "Globe2",
    },
    {
      date: "2025-12-23",
      name: "Icefish's Blood",
      description: "A fish with clear blood, adapted to extreme cold.",
      icon: "TestTube",
    },
    {
      date: "2025-12-24",
      name: "Christmas Eve's Hush",
      description: "A quiet, anticipatory stillness.",
      icon: "Gift",
    },
    {
      date: "2025-12-25",
      name: "Reindeer's Moss",
      description: "A vital, lichenous food source in the winter.",
      icon: "Shrub",
    },
    {
      date: "2025-12-26",
      name: "Boxing Day's Calm",
      description: "A day of rest after the holiday rush.",
      icon: "Box",
    },
    {
      date: "2025-12-27",
      name: "Frozen Bubble's Dance",
      description: "The beautiful, crystalline patterns on a frozen bubble.",
      icon: "Disc3",
    },
    {
      date: "2025-12-28",
      name: "Year's End Reflection",
      description: "Looking back at the seasons of growth and change.",
      icon: "History",
    },
    {
      date: "2025-12-29",
      name: "Final Sunset",
      description: "The last sunset of the year.",
      icon: "Sunset",
    },
    {
      date: "2025-12-30",
      name: "World's Turning",
      description: "The constant, reliable rotation of our planet.",
      icon: "RotateCw",
    },
    {
      date: "2025-12-31",
      name: "New Year's Seed",
      description: "The promise of another cycle, another chance to grow.",
      icon: "Sprout",
    },
  ]
  